# Generated by Django 4.0.4 on 2022-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eifapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
